### ISSUE TITLE
Logo?!

### ISSUE THREAD

**Issue by CBSti** [atomfrede/freifunk-lgs-2017#1]
Ein kleines Logo wäre doch ideal, möglicherweise eine Kombination aus dem Lippspringer Logo/Wappen und einem Symbol zum Hinweis auf WLAN o.ä.?

**Comment by atomfrede** [comment]
Das ist super. Ich habe da schon eine Idee :)

**Comment by atomfrede** [comment]
Erledigt, siehe [das Ergebnis](http://atomfrede.github.io/freifunk-lgs-2017/).
